### ISSUE TITLE
Little problems I've faced while checking out your project.

### ISSUE THREAD

**Issue by Eddudos** [DIMFLIX-OFFICIAL/AiogramStorages#1]
First of all, thanks for your library, it really helped me to deal with states quick using Postgredb.

I found these things to be incorrect in your README.md:
1. `pip install AiogramStorages` didn't really work for me, it throws an error like this 
![image](https://user-images.githubusercontent.com/43271573/231697565-5e9f7a9f-10be-4a30-970d-82b351943a8c.png)
but  `pip install AiogramStorages==1.0.0` solved that.

2. Typo in `from AiogramStotages.storages import ...`, it should be `from AiogramStorages.storages import ...`.

**Comment by DIMFLIX** [comment]
Thanks a lot for finding the bugs. Readme already corrected :)
